"""
send_email.py

Sends the trend report via Gmail SMTP using an App Password.
No OAuth required.

Setup:
  1. Enable 2-Step Verification on your Google account
  2. Go to myaccount.google.com/apppasswords
  3. Create an App Password named "YouTube Report"
  4. Add it to .env as GMAIL_APP_PASSWORD

Usage:
  python tools/send_email.py \
    --to recipient@example.com \
    --topic "AI for Business" \
    --deck-url "https://gamma.app/docs/..." \
    --report-brief "outputs/my-topic-2026-04/report_brief.md"
"""

import argparse
import os
import smtplib
import sys
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

GMAIL_FROM = os.getenv("REPORT_EMAIL", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def extract_executive_summary(report_brief_path: str) -> str:
    path = Path(report_brief_path)
    if not path.exists():
        return "See the slide deck for the full analysis."
    in_section = False
    summary_lines = []
    for line in path.read_text().split("\n"):
        if "## 1. EXECUTIVE SUMMARY" in line or "## EXECUTIVE SUMMARY" in line:
            in_section = True
            continue
        if in_section:
            if line.startswith("## "):
                break
            summary_lines.append(line)
    return "\n".join(summary_lines).strip() or "See the slide deck for the full analysis."


def build_html_body(topic: str, deck_url: str, summary: str, date_str: str) -> str:
    return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 20px; }}
    h1 {{ font-size: 22px; border-bottom: 2px solid #e0e0e0; padding-bottom: 12px; }}
    h2 {{ color: #333; font-size: 16px; margin-top: 24px; }}
    .cta {{ background: #1a1a2e; color: white; padding: 14px 28px; border-radius: 6px; text-decoration: none; font-weight: 600; display: inline-block; margin: 16px 0; }}
    .summary {{ background: #f8f9fa; border-left: 4px solid #1a1a2e; padding: 16px; border-radius: 0 6px 6px 0; font-size: 14px; line-height: 1.6; white-space: pre-wrap; }}
    .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 12px; color: #888; }}
  </style>
</head>
<body>
  <h1>{topic} — YouTube Trend Report</h1>
  <p><strong>Date:</strong> {date_str}</p>
  <p>Your YouTube trend analysis is ready. The slide deck covers trending topics, audience pain points, engagement patterns, and specific content ideas.</p>
  <h2>View Slide Deck</h2>
  <a href="{deck_url}" class="cta">Open Slide Deck →</a>
  <h2>Executive Summary</h2>
  <div class="summary">{summary}</div>
  <div class="footer">Generated by the YouTube Trend Analysis automation.</div>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--to", required=True, help="Recipient email address")
    parser.add_argument("--topic", required=True, help="Topic name for email subject")
    parser.add_argument("--deck-url", required=True, help="Gamma slide deck URL")
    parser.add_argument("--report-brief", required=True, help="Path to report_brief.md")
    args = parser.parse_args()

    if not GMAIL_FROM:
        print("ERROR: REPORT_EMAIL not set in .env (this is the Gmail address you're sending FROM)")
        sys.exit(1)
    if not GMAIL_APP_PASSWORD:
        print("ERROR: GMAIL_APP_PASSWORD not set in .env")
        print("Get one at: myaccount.google.com/apppasswords")
        sys.exit(1)

    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    subject = f"{args.topic} — YouTube Trend Report ({date_str})"
    summary = extract_executive_summary(args.report_brief)
    html_body = build_html_body(args.topic, args.deck_url, summary, date_str)

    msg = MIMEMultipart("alternative")
    msg["From"] = GMAIL_FROM
    msg["To"] = args.to
    msg["Subject"] = subject
    msg.attach(MIMEText(html_body, "html"))

    print(f"Sending to {args.to}...")
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(GMAIL_FROM, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_FROM, args.to, msg.as_string())
        print("Email sent successfully.")
    except smtplib.SMTPAuthenticationError:
        print("ERROR: Gmail authentication failed.")
        print("Check that GMAIL_APP_PASSWORD in .env is correct.")
        print("Get one at: myaccount.google.com/apppasswords")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
